### PR TITLE
(SIMP-10589) Update docs for new build process

### PR DESCRIPTION
**Pull request by trevor-vaughan**
Moved the ISO build docs out of the Getting Started Guide into the
Contributors Guide and updated to the 6.6+ build technique.

SIMP-10589 #close

### CODE REVIEW

**Comment by lnemsick-simp** [comment]
simp-rake-helpers logic does not allow the ISO to be built when packages.yaml is empty:
```
Created .../simp-core/build/distributions/CentOS/8/x86_64/yum_data
Created example file at .../simp-core/build/distributions/CentOS/8/x86_64/yum_data/packages.yaml
================================================================================
Failed ISOs:
  * CentOS 8 x86_64
    * Error:         Error: Could not find anything to do!

        In .../simp-core.tv/build/distributions/CentOS/8/x86_64/yum_data:
            No packages in either packages.yaml or the packages/ directory

```

**Comment by trevor-vaughan** [comment]
Welp, that's fun. I thought I fixed that in rake-helpers but I'll add an update to simp/rubygem-simp-rake-helpers#175 to get around if possible.

**Comment by trevor-vaughan** [comment]
@lnemsick-simp Looks like I already fixed this. Do you have a populated `reposync` directory? If there aren't any repos in there then things will fail because it either needs something from `reposync` or something to do in `packages.yaml`.

I'm currently in a fresh build so I'll see if it fails when I get there.

**Comment by lnemsick-simp** [comment]
repoclosure failed when I followed the procedures.  Rebuilt the reposync repositories from scratch a second time just to be sure, but still failed the same way.

**Pull request merged**
